[grafana]
loki = false
host = "logs-prod-020.grafana.net"

[notion]
pause_secs = 2

[github]
base_url = "https://api.github.com"
pause_secs = 2
username = "takassh"

[cloudflare]
base_url = "https://api.cloudflare.com"
generate_image_ai_path = "ai/run/@cf/bytedance/stable-diffusion-xl-lightning"
translation_ai_path = "ai/run/@cf/meta/m2m100-1.2b"
generate_text_ai_path = "ai/run/@cf/meta/llama-3-8b-instruct"
summarization_ai_path = "ai/run/@cf/facebook/bart-large-cnn"

[aws]
s3_url = "https://bucket.takassh.com"

[qdrant]
base_url = "https://37feeba7-135c-48c4-a8a9-93a52b2b1de7.us-east4-0.gcp.cloud.qdrant.io:6334"
collection = "notion"