//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod block;
pub mod event;
pub mod notion_database;
pub mod page;
pub mod post;
pub mod prompt;
pub mod prompt_page;
pub mod prompt_session;
pub mod sea_orm_active_enums;
pub mod static_page;
pub mod user;
