//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::block::Entity as Block;
pub use super::event::Entity as Event;
pub use super::notion_database::Entity as NotionDatabase;
pub use super::page::Entity as Page;
pub use super::post::Entity as Post;
pub use super::prompt::Entity as Prompt;
pub use super::prompt_session::Entity as PromptSession;
pub use super::static_page::Entity as StaticPage;
pub use super::user::Entity as User;
