//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prompt")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prompt_session_id: String,
    pub user_prompt: String,
    pub assistant_prompt: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub tools_prompt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
